version: '3.1'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:5.0.8
    restart: always
    volumes:
      - "/var/lib/docker/volumes/redis/data:/data:z"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    entrypoint: docker-entrypoint.sh --requirepass ${REDIS_PASSWORD}

  app:
    image: cu-uffs
    container_name: app
    build:
      context: ./../
      dockerfile: ./docker/app/.Dockerfile
    restart: always
    volumes:
      - ..:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      CONTAINER_ROLE: app
    entrypoint: ./docker/start.sh

  horizon:
    image: cu-uffs
    container_name: horizon
    restart: always
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: horizon
    entrypoint: ./docker/start.sh

  scheduler:
    image: cu-uffs
    container_name: scheduler
    restart: always
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: scheduler
    entrypoint: ./docker/start.sh

networks:
  snr:
    ipam:
      driver: default
