version: '3.1'

services:
  app:
    image: cu-uffs
    container_name: app
    build:
      context: ./../
      dockerfile: ./docker/.Dockerfile
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ..:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      CONTAINER_ROLE: app
    entrypoint: ./docker/start.sh

  horizon:
    image: cu-uffs
    container_name: horizon
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: horizon
    entrypoint: ./docker/start.sh

  scheduler:
    image: cu-uffs
    container_name: scheduler
    restart: always
    ports:
      - '8002:8002'
    volumes:
      - ..:/var/www/html
    depends_on:
      - app
    environment:
      CONTAINER_ROLE: scheduler
    entrypoint: ./docker/start.sh

networks:
  snr:
    ipam:
      driver: default
