version: '3.1'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Senha@2022
    networks:
        snr:
            ipv4_address: 172.16.238.10
networks:
    snr:
        ipam:
            driver: default
            config:
              - subnet: "172.16.238.0/24"
