version: '3.1'

services:
  redis:
    image: redis:5.0.8
    restart: always
    volumes:
        - "/var/docker/volumes/redis/data:/data:z"
    ports:
        - "6379:6379"
    networks:
        snr:
            ipv4_address: 172.16.238.30
    entrypoint: docker-entrypoint.sh --requirepass Senha@2022
networks:
    snr:
        ipam:
            driver: default
            config:
              - subnet: "172.16.238.0/24"

